name: Elm Tooling

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 19.x
          cache: npm
          cache-dependency-path: package-lock.json
      
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v3
        with: 
          path: pupperoni/node_modules
          key: node_modules-${{ hashfiles('package.json', 'package-lock.json') }}
          
      - name: Cache ~/.elm
        uses: actions/cache@v3
        with:
          path: ~/.elm
          key: elm-${{ hashFiles('elm.json', 'elm-tooling.json', 'review/elm.json') }}
          
      - name: npm ci
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        env:
          NO_ELM_TOOLING_INSTALL: 1
        run: npm ci
      
      - name: elm-tooling install
        run: npx elm-tooling install
        
      - name: elm make
        run: npx elm make src/Main.elm --optimize --output=app.js
        
      - name: elm-format
        run: npx elm-format --validate .
        
      - name: elm-review
        run: npx elm-review